#ifndef CONFIG_H
#define CONFIG_H

#define MAX_LINE_LENGTH 150
#define MAX_LABELS 200
#define RAM_SIZE 254
#define MIN_SPEED 0
#define MAX_SPEED 5
#define DEFAULT_SPEED 2
#define TEMPLATE "Template.vhd"
#define DEFAULT_TITLE "E80 Firmware, generated by the E80ASM Assembler"

#endif
